mapeo_columnas = {
    'SED_x': 'SED',
    'Suministro':'Suministro',
    'Nombre': 'Nombre',
    'Direccion':'Direccion',
    'Distrito':'Distrito',
    'Estado_Cliente':'Estado Cliente',
    'Medidor':'Medidor',
    'Marca':'Marca',
    'Fase':'Fase',
    'Factor':'Factor',
    'Giro_de_Sistema':'Giro de Sistema',
    'Tarifa': 'Tarifa',
    'Tipo_Acomet':'Tipo Acomet',
    'Llave':'Llave',
    'Ruta_de_Lectura':'Ruta de Lectura',
    'Ultima_Lectura_Terreno':'Ultima Lectura',
    'Fecha_Ultima_Lectura_Terreno':'Fecha Ultima Lectura',
    'Ultimo_Consumo':'Ultimo Consumo',
    'Clave_Ult_LectFact':'Clave_Ult LectFact',
    'Consumo_9':'Consumo_9',
    'Consumo_8':'Consumo_8',
    'Consumo_7':'Consumo_7',
    'Consumo_6':'Consumo_6',
    'Consumo_5':'Consumo_5',
    'Consumo_4':'Consumo_4',
    'Consumo_3':'Consumo_3',
    'Consumo_2':'Consumo_2',
    'Consumo_1':'Consumo_1',
    'Lectura_1':'Lectura_1',
    'Lectura_2':'Lectura_2',
    'Observaciones':'Observaciones',
    'Causal':'CAUSAL',
    'Giro_de_Sistema_1':'Giro Sistema',
    'Tipo_Acomet_1':'Tipo_Acomet',
    'Tipo_de_Medidor':'Tipo de Medidor'
}